name: EDK2 Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential uuid-dev nasm gcc-10 g++-10 iasl

    - name: Build EDK2
      run: |
        git clone https://github.com/tianocore/edk2.git
        git clone https://github.com/piashmsubd/TWRP_NX669J_12.1.git device/nubia/nx669j
        cd edk2
        git submodule update --init
        make -C BaseTools
        . edksetup.sh
        build -a X64 -t GCC5 -p MdeModulePkg/MdeModulePkg.dsc

    - name: Check Build Folder
      run: |
        ls ./Build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: edk2-build
        path: ./Build
