name: SSH Access
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          sudo apt update
          sudo apt -y install openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh
          hostname -I
          ping 172.17.0.1

          whoami
          sudo ufw allow ssh
          ssh-keygen -t rsa -b 4096 -C "gooogleabal@gmail.com" -f ~/.ssh/id_rsa -N ""
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
